default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cryptobowl_development 
  adapter: postgresql
  username: cryptobowl
  password: <%= ENV['cryptobowl_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: cryptobowl_test     
  adapter: postgresql
  username: cryptobowl
  password: <%= ENV['cryptobowl_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: cryptobowl_production   
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>